---
- name: Configure IPS policies
  hosts: mysrx
  connection: local
  gather_facts: no
  vars:
    junos_user: "root"
    junos_password: "Juniper"
    build_dir: "/tmp/"
    address_entries: [ {'name':'NetDevOpsVM','prefix':'172.16.0.1/32'} ]
    idp_policy_info: [{"policy_name":"ips-policy1","rules":{"name":"rule1","src_zone":"trust","dst_zone":"untrust","src_ips":["any"],"dst_ips":["any"],"apps":["default"],"action":"drop-connection","severity","critical"}]

  tasks:
    - name: Build address book entries
      template: src=templates/fw_address_book.set.js dest={{build_dir}}/fw_address_book.set
      with_items: address_entries

    - name: Apply address book entries
      junos_install_config: host={{ inventory_hostname }} user={{ junos_user }} passwd={{ junos_password }} file={{ build_dir }}/fw_address_book.set overwrite=no logfile=logs/{{ inventory_hostname }}.log

    - name: Build ips policies config template
      template: src=templates/idp_policy.set.js dest={{build_dir}}/idp_policy.set
      with_items: ips_policy_info

    - name: Apply ips policies
      junos_install_config: host={{ inventory_hostname }} user={{ junos_user }} passwd={{ junos_password }} file={{ build_dir }}/idp_policy.set overwrite=no logfile=logs/{{ inventory_hostname }}.log
